### ISSUE TITLE
[Bug]: sharp image lib. Image upload and thumbnail regeneration: ERR_IPC_CHANNEL_CLOSED

### ISSUE THREAD

**Issue by sysbpfeiffer** [GetPublii/Publii#2171]
### Operating system

Fedora 42

### Publii version

0.46.4

### Post editor

Block editor

### Bug description

Hello I'm suddenly getting this error when trying to re-generate thumbnails.
No publii or theme update. Happens suddenly but persistent.

![Image](https://github.com/user-attachments/assets/07d372d0-4e46-4e7a-9dfc-9d4f0c51e346)

It had to switch to Jimp for image generation to make it work again. I just wonder why this is happening.

Currently, I cannot use the wepp generation

### Steps to reproduce

Trying to upload a picture or re-generate thumbnails with sharp active.

### Relevant log output

```shell
Bail out! ERROR:/__w/sharp/sharp/node_modules/@img/sharp-libvips-dev/include/vips/VImage8.h:134:vips::VObject& vips::VObject::operator=(const vips::VObject&): assertion failed: (!a.vobject || VIPS_IS_OBJECT(a.vobject))
Bail out! ERROR:/__w/sharp/sharp/node_modules/@img/sharp-libvips-dev/include/vips/VImage8.h:134:vips::VObject& vips::VObject::operator=(const vips::VObject&): assertion failed: (!a.vobject || VIPS_IS_OBJECT(a.vobject))
Bail out! ERROR:/__w/sharp/sharp/node_modules/@img/sharp-libvips-dev/include/vips/VImage8.h:134:vips::VObject& vips::VObject::operator=(const vips::VObject&): assertion failed: (!a.vobject || VIPS_IS_OBJECT(a.vobject))
```

**Comment by dziudek** [comment]
Hi,

Please redownload the Publii v.0.46.4 - we have released a hot fix which addresses this issue a few days ago

**Comment by ryder203** [comment]
<img width="519" alt="Image" src="https://github.com/user-attachments/assets/309c2e36-0550-4516-b0c8-810efe4e5cca" />

Same here on latest Windows 11 Pro build.

**Comment by ryder203** [comment]
Redownloaded the installer exe, but it is not fixed. Really thinking about going back to Wordpress. It's a slower CMS, but at least it's stable and reliable.

**Comment by sysbpfeiffer** [comment]
Can confirm, it works again in linux after re-downloading the 0.46.4.
I'm using the appimage version. I just wonder how an appimage can change its behaviour. I thought it contains all its dependencies statically.

**Comment by YoavRheims** [comment]
I'm having the same bug with version 0.47.3 (build 17367) on Fedora, had to revert to Jimp and disable webp.
